### ISSUE TITLE
Can't import logged performance

### ISSUE THREAD

**Issue by CrashServer** [Qirky/Troop#45]
there are problems with the logged performance player, in the `logfile.py` .

first with Python3 we need to change line 22 :
`message = bytes(message.strip()[1:-1], "utf-8").decode('unicode_escape')`

after I'm stuck with line 24 and the `NetworkMessage()` class

**Comment by Qirky** [comment]
Unfortunately this feature has been broken since 2018 when a new method for connecting and adding text was added. It was added as an experimental debug feature but is no longer supported. I've spent some time looking at it and it might be quite difficult to do so is currently  left unsupported for now

**Comment by Qirky** [comment]
I'm actually removing this feature for now as it doesn't work but might continue to look at the  feature  branch down the line
